# =============================
# VRChat OSC Sync Configuration
# =============================

[settings]
# Set to true if this computer is hosting.
# The host must port forward the desired port, 38955 by default.
is_host = False

# If you aren't hosting, put your hosts ip here
friend_ip = 127.0.0.1

# You can choose a custom port. Make sure everyone is using the same port.
ws_port = 38955

# As a security measure you can have a custom password. Use letters and numbers only.
#secretpassword = nospecialsymbols

# If you are finding your connection with your friends laggy, make this number higher
#ping_compensation = 1.5

# If you would like to prevent a certain parameter from going through you may blacklist it
blacklist = ""
blacklist_sending = ""
blacklist_receiving = ""

# Alternatively, if you have a whitelist it will ignore everything unless it is on here
whitelist = ""


#cooldown = 0.03

